### ISSUE TITLE
std::isspace requires unsigned

### ISSUE THREAD

**Issue by OlafvdSpek** [boostorg/convert#28]
```
boost\convert\base.hpp(112): warning C6330: 'const char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.

boost\convert\base.hpp(115): warning C6330: 'const char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.
```

**Comment by yet-another-user** [comment]
Much appreciated. I'll have it addressed ASAP.

**Comment by yet-another-user** [comment]
Much appreciated. I'll have it addressed ASAP.

**Comment by yet-another-user** [comment]
Unm, I presume is MS Visual Studio. What version is it? The standard POSIX signature of the function is
    int isspace(int c) 
It is defined in 
    #include <ctype.h>
via the cctype header.

Seems like MS have it messed it up. What am I missing?

**Comment by OlafvdSpek** [comment]
http://en.cppreference.com/w/cpp/string/byte/isspace

```
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
```

**Comment by yet-another-user** [comment]
1. We get a compilation warning "unsigned char is required in call to 'isspace". I believe it is wrong for the compiler to issue such a warning because "int is actually required by isspace". So, technically, 'char' is fine (auto-promoted to int).

2. The statement "behavior is undefined if the value of ch is not representable as unsigned char" describes the internal run-time function behavior. However, it does not expect "unsigned char" as the compiler claims. For example, EOF is not "unsigned char". It means that if the supplied "int" goes out of [-1,256) range, then "behavior is undefined". Consequently, I expect

char ch;
isspace(ch);

to be a valid piece of code at compile-time because it matches the isspace(int) signature (char is promoted to int).

At run-time it is valid as long as 'ch' is ANSII [0,127].

The problem will arise if, say, ch=-55. However, the compiler cannot pick it up. It'll be an internal run-time "undefined behavior".

Do you agree?

**Comment by OlafvdSpek** [comment]
The error is from a code analyzer, not from the compiler. But yeah, negative values will cause undefined behavior.

**Comment by yet-another-user** [comment]
Uh, a code analyzer. Fair enough. So, the compiler is innocent then. Good. :-) So, technically, compilation-wise the code is correct and there seem nothing to fix. Then, yes, the code analyzer warns us of the std::isspace() function vulnerability... which is fair enough too. I suspect the necessary validation checks are outside boost::convert scope. Do you agree?

**Comment by OlafvdSpek** [comment]
No, undefined behavior here is unacceptable.
I don't know the right solution, I've used `v & 0xff` myself. A static_cast<unsigned> might work as well, perhaps you should ask on the mailing list.

**Comment by yet-another-user** [comment]
Correction: there is no undefined behavior here, i.e. in boost::convert. The undefined behavior is in isspace(). Now you are essentially saying that if the user (on one side) messed it up and isspace() (on the other side) does not like it, then it is the middle-man (boost::convert) responsibility to clean it all up. I am not sure I am prepared to accept that. I'll have to think about it. Thanks for the input all the same.

**Comment by OlafvdSpek** [comment]
> Correction: there is no undefined behavior here, i.e. in boost::convert. 

How so?
Does boost::convert have preconditions that forbid input having 'negative' chars?

**Comment by yet-another-user** [comment]
There are 3 participants -- the caller, boost::convert, isspace(). It is the isspace() that introduces the undef. behavior but does not address that. Still, you seem you believe it's boost::convert task to address that. I am not sure I am that definitive about that. :-)

**Comment by OlafvdSpek** [comment]
No, it is convert that violates preconditions of isspace..

**Comment by yet-another-user** [comment]
isspace does not have preconditions to violate. boost::convert does not "have preconditions that forbid input having 'negative' chars" (quoting you). Just as isspace() does not have any preconditions. If instead, you insist that isspace() does have preconditions, then so boost::convert. In other words, boost::convert has (or does not have) preconditions just as isspace. So, if isspace does have those, then it is the user who violates those. Isn't it? Or no matter what it is always boost::convert's fault? :-)

**Comment by OlafvdSpek** [comment]
Yes ;)

` In other words, boost::convert has (or does not have) preconditions just as isspace.`

OK, so where are those preconditions of boost::convert documented?

**Comment by yet-another-user** [comment]
... documented

That's a valid point... but lacking/insufficient documentation is somewhat
different from a bug in the actual code. I'll keep it mind though to
address.


On Sun, Mar 19, 2017 at 9:31 PM, Olaf van der Spek <notifications@github.com

**Comment by yet-another-user** [comment]
Done

**Comment by OlafvdSpek** [comment]
Boost 1.64 does not contain this fix, does it? :(

**Comment by yet-another-user** [comment]
Unfortunately it is correct. In late March 1.64 was already closed for changes (or so I understood). So, I did not merge the changes into the master branch. 1.65 is now open, so I did it now. I am sorry.

**Comment by OlafvdSpek** [comment]
1.64 was open for fixes after March 24th.. this should've been included.

**Comment by yet-another-user** [comment]
By Rene Rivera 09MAR17: "The master branch is now closed for all changes except by permission for the Beta release". 

If 1.64 was, in fact, open as you indicated, then I misinterpreted that statement above. My most humble apologies.

**Comment by OlafvdSpek** [comment]
> On 24-03-17 02:00, Rene Rivera via Boost wrote:
> The master branch is is now open for post-beta merges, but only as
> described in the Post-Beta Merge Policy. See <
> https://github.com/boostorg/boost/wiki/Release-Beta-Merge-Policy>

**Comment by OlafvdSpek** [comment]
Just to verify, is it in master yet?

**Comment by yet-another-user** [comment]
Yes, the develop branch has been merged into the master some time ago. Unfortunately, it was late for 1.64 as we discussed.
