### ISSUE TITLE
convert_test_performance failed to link for <link>shared

### ISSUE THREAD

**Issue by BinCaoWR** [boostorg/convert#46]
clang-vxworks.link ../bin.v2/libs/convert/test/clang-vxworks/debug/cross-compile-vxworks/convert_test_performance.vxe
/llvm-8.0.0.1/LINUX64/bin/ldpentium: warning: ../bin.v2/libs/chrono/build/clang-vxworks/debug/cross-compile-vxworks/libboost_chrono.so.1.70.0, needed by ../bin.v2/libs/timer/build/clang-vxworks/debug/cross-compile-vxworks/libboost_timer.so.1.70.0, not found (try using -rpath or -rpath-link)
/llvm-8.0.0.1/LINUX64/bin/ldpentium: ../bin.v2/libs/timer/build/clang-vxworks/debug/cross-compile-vxworks/libboost_timer.so.1.70.0: undefined reference to `boost::chrono::steady_clock::now()'

 /llvm-8.0.0.1/LINUX64/bin/ldpentium -m elf_x86_64 -L"/usr/lib/common" -o "../bin.v2/libs/convert/test/clang-vxworks/debug/cross-compile-vxworks/convert_test_performance.vxe" --defsym __wrs_rtp_base=0x200000 -u __wr_need_frame_add -u __tls__ -T/usr/ldscripts/rtp.ld /usr/lib/common//crt0.o "../bin.v2/libs/convert/test/clang-vxworks/debug/cross-compile-vxworks/performance.o" "../bin.v2/libs/timer/build/clang-vxworks/debug/cross-compile-vxworks/libboost_timer.so.1.70.0" --as-needed -E --start-group -lunix -lnet  -lc  -lc_internal  -lllvm  -lcplusplus  -lllvmcplus  -ldl     --end-group     

...failed clang-vxworks.link ../bin.v2/libs/convert/test/clang-vxworks/debug/cross-compile-vxworks/convert_test_performance.vxe...

The link can succeed after I updated following line in libs/convert/test/jamfile.v2.

From:
exe convert_test_performance : performance.cpp /boost/timer//boost_timer ;
To:
exe convert_test_performance : performance.cpp /boost/timer//boost_timer /boost/chrono//boost_chrono ;

**Comment by yet-another-user** [comment]
Thank you for your input. Much appreciated. I admit I know nothing about jamfile. Someone from the infrastructure management team added it. If you could provide a merge request, I'd gladly merge. Thanks in advance.

**Comment by BinCaoWR** [comment]
Glad to do. The pull request created.

**Comment by yet-another-user** [comment]
Much appreciated. Thanks again.
